### ISSUE TITLE
Upload error when importing android.ocs inventory file 

### ISSUE THREAD

**Issue by BlackSpartan** [hschletz/Braintacle#3]
Good Day @hschletz 
1. I managed to install the communication server however when I am importing an androind.ocs file I am receiving an error message saying 

> Upload error. Server http://localhost/braintacle-server responded with error 500: Internal Server Error

below is the screenshot of the error message

> ![braintacle](https://user-images.githubusercontent.com/39332901/121507815-fcf1d180-c9b2-11eb-8712-ace9a04addb3.png)

2. When I run `sudo apache2ctl configtest` In my apache2 error logs I get this 

> ocsinventory-server: Can't load SOAP::Transport::HTTP* - Web service will be unavailable
Syntax OK

**Comment by hschletz** [comment]
Here's an inventory file which definitely works. You can unzip and import it and see if this gets accepted.
[android-2021-06-10-19-34-23.ocs.zip](https://github.com/hschletz/Braintacle/files/6633621/android-2021-06-10-19-34-23.ocs.zip)

> When I run sudo apache2ctl configtest In my apache2 error logs I get this
ocsinventory-server: Can't load SOAP::Transport::HTTP* - Web service will be unavailable
Syntax OK

Have you installed an OCSInventory-NG server on the same Apache instance? This is known to generate that message, which is in itself harmless. Braintacle (which runs a fork of the OCSInventory-NG server under the /braintacle-server URL) has that part of the Code removed and will not generate the message.

Unless you have configured a logfile, the server logs to syslog. You should see some messages in /var/log/messages, via journalctl or wherever your syslog messages go. You can also enable slightly more verbose logging via the console ("Preferences"->"System"->"Log level").

Also check out your database server log for errors.

**Comment by BlackSpartan** [comment]
inventory file is accepted.
I removed OCSInventory-NG and the error message no longer exists.
I wanted to ask some few questions on the technology stack you used on your project but I cant find your contact address.
Why did you use Laminas framework?

**Comment by hschletz** [comment]
> inventory file is accepted.
> I removed OCSInventory-NG and the error message no longer exists.

Do you mean that the problem was solved entirely by removing OCSInventory-NG, or does only the provided sample file work, and the problem persists with your own inventory file?

> I wanted to ask some few questions on the technology stack you used on your project but I cant find your contact address.
> Why did you use Laminas framework?

I'll contact you per mail.

**Comment by BlackSpartan** [comment]
> Do you mean that the problem was solved entirely by removing OCSInventory-NG, or does only the provided sample file work, and the problem persists with your own inventory file?

l checked my database server log for errors and I found out that I was denied access since the application was trying to import the file to ocsweb database instead of braintacle. after deleting the ocsweb I managed to upload both files.
![a](https://user-images.githubusercontent.com/39332901/122272588-abfc4480-ceae-11eb-96b2-c668c8118f5a.png)

> I'll contact you per mail.

Here is my email address shokomelu@gmail.com
