### ISSUE TITLE
Identifying duplicate records with just a click.

### ISSUE THREAD

**Issue by BlackSpartan** [hschletz/Braintacle#4]
Dear @hschletz 

Is it possible to have a feature that group records that are duplicate using color coding? if yes how can that be achieved.
for example if I click record with ID 7 it shows me that it is identical with record with ID 9.
![duplicate](https://user-images.githubusercontent.com/39332901/122649228-2e923780-d12d-11eb-93c0-049eecf50f54.png)

**Comment by hschletz** [comment]
I don't understand what could be improved here. Could you edit the screenshot to demonstrate what you want to have colorized and how?

In practice, the duplicates list will rarely grow too much as long as it receives occasional maintenance. False positives can be reduced by clicking on bogus serials, asset tags or MAC addresses, adding them to a list of ignored values. Duplicate names should never happen in a well organized network.

Once these things have been sorted out, the only situation where duplicates happen is after reinstallation of a device, when the newly installed agent no longer has access to its previous configuration and reports as a new device.

**Comment by BlackSpartan** [comment]
Ok thanks for the insight. There is no point of adding the feature.
